### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by UnEnanoMas** [Sonsa04/Crossbow#1]
Server thread/CRITICAL RuntimeException: "Trying to overwrite an already registered item" (EXCEPTION) in "src/pocketmine/item/ItemFactory" at line 298
08.04 21:12:09 [Server] Server thread/DEBUG #0 plugins/Crossbow-master/src/SonsaYT/Crossbow/Main(15): pocketmine\item\ItemFactory::registerItem(object SonsaYT\Crossbow\item\Crossbow)
08.04 21:12:09 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginBase(115): SonsaYT\Crossbow\Main->onEnable()
08.04 21:12:09 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
08.04 21:12:09 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object SonsaYT\Crossbow\Main)
08.04 21:12:09 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object SonsaYT\Crossbow\Main)
08.04 21:12:09 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1852): pocketmine\Server->enablePlugins(integer 1)
08.04 21:12:09 [Server] Server thread/DEBUG #6 src/pocketmine/command/defaults/ReloadCommand(49): pocketmine\Server->reload()
08.04 21:12:09 [Server] Server thread/DEBUG #7 src/pocketmine/command/SimpleCommandMap(248): pocketmine\command\defaults\ReloadCommand->execute(object pocketmine\Player, string[6] reload, array[0])
08.04 21:12:09 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1807): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[6] reload)
08.04 21:12:09 [Server] Server thread/DEBUG #9 src/pocketmine/Player(2201): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[6] reload)
08.04 21:12:09 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[7] /reload)
08.04 21:12:09 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
08.04 21:12:09 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
08.04 21:12:09 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
08.04 21:12:09 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
08.04 21:12:09 [Server] Server thread/DEBUG #15 src/pocketmine/Player(3096): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
08.04 21:12:09 [Server] Server thread/DEBUG #16 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
08.04 21:12:09 [Server] Server thread/DEBUG #17 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[16] 81.0.47.74 28481, object raklib\protocol\EncapsulatedPacket, integer 0)
08.04 21:12:09 [Server] Server thread/DEBUG #18 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
08.04 21:12:09 [Server] Server thread/DEBUG #19 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
08.04 21:12:09 [Server] Server thread/DEBUG #20 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
08.04 21:12:09 [Server] Server thread/DEBUG #21 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
08.04 21:12:09 [Server] Server thread/DEBUG #22 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1586380327.6942)
08.04 21:12:09 [Server] Server thread/DEBUG #23 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
08.04 21:12:09 [Server] Server thread/DEBUG #24 src/pocketmine/Server(1584): pocketmine\Server->start()
08.04 21:12:09 [Server] Server thread/DEBUG #25 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
08.04 21:12:09 [Server] Server thread/DEBUG #26 src/pocketmine/PocketMine(296):

**Comment by Sonsa04** [comment]
What's your pmmp version?

**Comment by UnEnanoMas** [comment]
> What's your pmmp version? coz it seems that you already have crossbow.
> Try to download it again, I updated it

Ok :) This problem its like when i do /reload but he only appear 1 time of so many /reload

**Comment by Sonsa04** [comment]
Download the latest update & don't use /reload
